---
# File: tasks/main.yml - Hoodie role tasks

- name: Hoodie user
  sudo: True
  user: "name={{ hoodie_admin }} home={{ hoodie_dir }} comment='Hoodie administrator' shell=/bin/bash"
  tags:
    - hoodie_user

- name: Hoodie user limits
  sudo: True
  template: "src=hoodie.limits.j2 dest=/etc/security/limits.d/hoodie"
  tags:
    - hoodie_user

- name: Install OS packages
  sudo: True
  apt: "name={{ item }} update_cache=yes"
  with_items: hoodie_os_packages
  tags:
    - system_packages

- name: Install Node Version Manager
  sudo: True
  git: "repo=https://github.com/creationix/nvm.git dest={{ hoodie_nvm_dir }} accept_hostkey=yes"
  tags:
    - nodejs

- name: Install Node.js
  sudo: True
  shell: "source {{ hoodie_nvm_dir }}/nvm.sh && nvm install {{ hoodie_node_version }} creates={{ hoodie_node_dir }} executable=/bin/bash"
  tags:
    - nodejs

- name: Install Hoodie
  sudo: True
  npm: "name={{ item }} executable={{ hoodie_node_dir }}/bin/npm path={{ hoodie_dir }} global=yes state=present"
  with_items: hoodie_node_packages
  tags:
    - nodejs

- name: Log rotation configuration
  sudo: True
  file: "src=hoodie-logrotate dest=/etc/logrotate.d/hoodie}}"

- name: Monit configuration
  sudo: True
  template: "src=hoodie-monit.j2 dest=/etc/monit.d/hoodie}}"
  tags: monit

- name: Correct permissions
  file: "path={{ hoodie_dir }} owner={{ hoodie_admin }} recurse=yes"

- name: Start CouchDB
  sudo: True
  service: name=couchdb state=started
  tags: couchdb

- name: Install SSL cert and key
  file: "src=_{{ hoodie_app_domain }}.chained.crt dest=/etc/ssl/{{ hoodie_app_domain }}/{{ hoodie_app_domain }}.chained.crt"
  file: "src=_{{ hoodie_app_domain }}/{{ hoodie_app_domain }}.key dest=/etc/ssl/{{ hoodie_app_domain }}/{{ hoodie_app_domain }}.key"
  tags: nginx

- name: Configure Nginx virtual host
  template: "src=hoodie-nginx.conf.j2 dest=/etc/nginx/vhosts.d/{{ hoodie_app_name }}.conf}}"
  tags: nginx

- name: Start Nginx
  sudo: True
  service: name=nginx state=restarted
  tags: nginx
