# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for bootstrapping a Hubot instance on Mac OS X with Vagrant
# provider and Ansible provisioiner on Ubuntu virtual machine

VAGRANTFILE_API_VERSION = "2"
BOX_MEM = ENV['BOX_MEM'] || "2048"
BOX_NAME =  ENV['BOX_NAME'] || "ubuntu/trusty64"
HOODIE_HOST = ENV['HOODIE_HOST'] || "vagrant_hosts"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :hoodie do |hoodie_config|
    hoodie_config.vm.box = BOX_NAME
    hoodie_config.vm.network :private_network, ip: "10.1.1.74"
    hoodie_config.vm.hostname = "hoodie.local"
    hoodie_config.ssh.forward_agent = true
    hoodie_config.vm.provider "virtualbox" do |v|
      v.name = "hoodie"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    hoodie_config.vm.provision :ansible do |ansible|
      ansible.inventory_path = HOODIE_HOST
      ansible.playbook = "site.yml"
    end
  end
end
